# Documentation can be found here https://github.com/GoogleContainerTools/container-structure-test
schemaVersion: "2.0.0"

fileExistenceTests:
  - name: 'Jar File'
    path: '/ms-evidence-handler.jar'
    shouldExist: true

metadataTest:
  entrypoint: [ "java", "-jar", "/ms-evidence-handler.jar"]
